### ISSUE TITLE
关于微信小程序加密的改变

### ISSUE THREAD

**Issue by vioren** [Seayon/Wxtyt_POST_DATA#2]

**Comment by Seayon** [comment]
已更新啦

**Comment by vioren** [comment]
@Seayon 谢老哥，还有你博客新写的PacketCapture那个app是我汉化去广告精简体积并且增加了文本框的复制。。猿粪NA
<http://vioren.space/archives/packetcapture/>

**Comment by Seayon** [comment]
很厉害。
